language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '7'
before_script:
  - npm prune
script:
  - ng build --prod --base-href "https://anuragsinghbisht.github.io/Angular2_FrontEnd/"
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
